matchBlocks=neepmeat:base_machine_block
connectBlocks=neepmeat:skin_machine_block
method=overlay
tiles=<skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> 1.png <skip>
faces=north south east west