matchBlocks=neepmeat:base_machine_block
connectBlocks=neepmeat:meat_steel_machine_block neepmeat:meat_steel_machine_block_2
method=overlay
tiles=<skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> <skip> 0.png <skip>
faces=north south east west